kind: pipeline
name: default

steps:
  - name: build
    image: node:16
    commands:
      - npm ci
      - bash ./ci/gh-pages.sh
      - bash ./ci/update-readme.sh
    environment:
      DECRYPT_KEY:
        from_secret: "DECRYPT_KEY"
      COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
      DEPLOY_DIR: "dist"
    when:
      branch:
        - master